import Foundation

// Dictionaries are immutable after init but Swift 6 flags `static let` on a
// generic container as potential global mutable state. The values never
// change at runtime, so `nonisolated(unsafe)` is correct here.
enum L10nTables {
    nonisolated(unsafe) static let english: [L10n.Key: String] = [
        .settingsLanguage:                "Language",
        .settingsPermissions:             "Permissions",
        .settingsBehavior:                "Behavior",
        .settingsPrivacy:                 "Privacy",
        .settingsAdvanced:                "Advanced",
        .fieldLaunchAtLogin:              "Launch at login",
        .fieldShowMenuBarIcon:            "Menu bar icon",
        .fieldWindowScope:                "Window scope",
        .fieldPreviewMode:                "Preview mode",
        .fieldSortOrder:                  "Sort order",
        .fieldHiddenApps:                 "Hidden apps",
        .fieldHiddenAppsHelp:             "Names and bundle IDs are case-insensitive. Plain entries match substrings; prefix an entry with = for an exact match. Separate entries with commas, semicolons, or new lines.",
        .hiddenAppsParsedSummary:         "Parsed rules: %d substring, %d exact",
        .fieldReducedMotion:              "Reduced motion",
        .fieldPerformanceLogging:         "Performance logging",
        .fieldResetAppearance:            "Reset appearance",
        .settingsHotkey:                  "Hotkey",
        .settingsBackground:              "Background",
        .settingsBadgeBar:                "Badge bar",
        .settingsSelection:               "Selection",
        .settingsPreviewSize:             "Preview size",
        .settingsObjectSelector:          "Object Selector",

        .fieldLanguage:                   "Language",
        .launchAtLoginStatusEnabled:      "On",
        .launchAtLoginStatusDisabled:     "Off",
        .launchAtLoginStatusRequiresApproval:"Needs approval in System Settings",
        .launchAtLoginStatusUnavailable:  "Not available on this macOS version",
        .launchAtLoginStatusUpdateFailed: "Change failed; previous state restored",
        .actionOpenLoginItemsSettings:    "Open Login Items Settings",
        .fieldModifier:                   "Modifier",
        .fieldTriggerKey:                 "Trigger key",
        .fieldActiveCombo:                "Active: %@",
        .fieldDoubleModifierSwitch:       "Quick previous-app shortcuts",
        .fieldDoubleModifier:             "Double modifier",
        .shortcutConflictSpotlight:       "Command-Space is reserved for Spotlight. Choose another shortcut.",
        .shortcutConflictInputSource:     "Control-Space is reserved for switching input sources. Choose another shortcut.",
        .fieldColor:                      "Color",
        .fieldOpacity:                    "Opacity",
        .fieldColorStrength:              "Color strength",
        .fieldPosition:                   "Position",
        .fieldAppIconColor:               "App icon color",
        .fieldIconSize:                   "Icon size",
        .fieldTextSize:                   "Text size",
        .fieldVerticalPadding:            "Vert. padding",
        .fieldAnimation:                  "Animation",
        .fieldHighlightColor:             "Highlight color",
        .fieldStrength:                   "Strength",
        .fieldWidth:                      "Width",
        .fieldMaxWidth:                   "Maximum width",
        .actionSnapWindow:                "Snap window",
        .actionSnapLeft:                  "Left",
        .actionSnapRight:                 "Right",
        .actionSnapTop:                   "Up",
        .actionSnapBottom:                "Down",
        .actionCloseWindow:               "Close window",
        .accessibilityWindowTileHint:     "Selects this window",
        .accessibilityApplicationTileHint:"Activates this application",
        .windowStateMinimized:            "Minimized",
        .windowStateApplication:          "Application",

        .permissionMessageAccessibility:  "Enable Accessibility for the global switcher and window controls.",
        .permissionMessageScreenRecording:"Enable Screen Recording for live window previews.",
        .permissionMessageBoth:           "Enable Accessibility and Screen Recording for the full experience.",
        .permissionNameAccessibility:     "Accessibility",
        .permissionNameScreenRecording:   "Screen Recording",
        .permissionActionOpenSettings:    "Open System Settings",
        .permissionActionOpenSettingsShort:"Open Settings",

        .alertPermissionTitle:            "SwitchBlade needs permission: %@",
        .alertPermissionBody:             "SwitchBlade requires permission to operate. Missing permissions: %@. Open the relevant System Settings page and enable SwitchBlade.",
        .alertOpenSettings:               "Open Settings",
        .alertLater:                      "Later",

        .modifierCommand:                 "⌘ Command",
        .modifierOption:                  "⌥ Option",
        .modifierControl:                 "⌃ Control",

        .keyTab:                          "Tab",
        .keyBacktick:                     "Backtick (`)",
        .keySpace:                        "Space",

        .windowScopeCurrentSpace:         "Current Space",
        .windowScopeAllSpaces:            "All Spaces",
        .windowScopeCurrentApp:           "Current app",

        .previewModeLive:                 "Live previews",
        .previewModeBlurred:              "Blur previews",
        .previewModeIconsOnly:            "Icons only",

        .sortRecentlyUsed:                "Recently used",
        .sortAppGrouped:                  "Group by app",
        .sortAlphabetical:                "Alphabetical",

        .loggingOff:                      "Off",
        .loggingBasic:                    "Basic",
        .loggingDebug:                    "Debug",

        .selectionPump:                   "Pump",
        .selectionBreathe:                "Breathe",
        .selectionBounce:                 "Bounce",
        .selectionFloat:                  "Float",
        .selectionWobble:                 "Wobble",

        .badgeBottom:                     "Bottom",
        .badgeTop:                        "Top",

        .menuSecureInputOff:              "Secure Input: Off",
        .menuSecureInputActive:           "Secure Input: %@ (pid %@)",
        .menuSecureInputStale:            "Secure Input: stuck pid %@",
        .menuSecureInputClear:            "Clear stuck Secure Input",
        .menuSecureInputClearUnavailable: "No safe Secure Input cleanup",
        .menuPermissions:                 "Permissions required",
        .menuOpenPermissionSettings:      "Open %@ Settings…",
        .menuSettings:                    "Settings…",
        .menuAbout:                       "About SwitchBlade",
        .menuQuit:                        "Quit SwitchBlade",
        .menuSettingsWindowTitle:         "SwitchBlade Settings",
        .menuEdit:                        "Edit",
        .menuWindow:                      "Window",
        .menuHelp:                        "Help",
        .menuServices:                    "Services",
        .menuHide:                        "Hide SwitchBlade",
        .menuHideOthers:                  "Hide Others",
        .menuShowAll:                     "Show All",
        .menuUndo:                        "Undo",
        .menuRedo:                        "Redo",
        .menuCut:                         "Cut",
        .menuCopy:                        "Copy",
        .menuPaste:                       "Paste",
        .menuSelectAll:                   "Select All",
        .menuMinimize:                    "Minimize",
        .menuZoom:                        "Zoom",
        .menuBringAllToFront:             "Bring All to Front",
        .tooltipSettings:                 "Settings",
        .tooltipSecureInputActive:        "Secure Input is active in %@ (pid %@). Cmd+Tab may fall back to macOS.",
        .tooltipSecureInputStale:         "Secure Input is stuck on stale pid %@. Use the SwitchBlade menu cleanup.",
        .accessibilityStatusItemLabel:    "SwitchBlade status menu",
        .accessibilityStatusItemHelp:     "Opens SwitchBlade settings, permission status, and app controls.",
        .accessibilitySwitcherPanelLabel: "SwitchBlade window switcher",
        .aboutBuiltAt:                    "Built"
    ]

    nonisolated(unsafe) static let finnish: [L10n.Key: String] = [
        .settingsLanguage:                "Kieli",
        .settingsPermissions:             "Käyttöoikeudet",
        .settingsBehavior:                "Toiminta",
        .settingsPrivacy:                 "Yksityisyys",
        .settingsAdvanced:                "Lisäasetukset",
        .fieldLaunchAtLogin:              "Avaa kirjautuessa",
        .fieldShowMenuBarIcon:            "Valikkorivin kuvake",
        .fieldWindowScope:                "Ikkunoiden rajaus",
        .fieldPreviewMode:                "Esikatselutila",
        .fieldSortOrder:                  "Järjestys",
        .fieldHiddenApps:                 "Piilotetut sovellukset",
        .fieldHiddenAppsHelp:             "Nimiä ja pakettitunnisteita verrataan kirjainkoosta riippumatta. Tavallinen merkintä etsii osumaa nimen sisältä; =-alku vaatii täsmällisen osuman. Erottele merkinnät pilkulla, puolipisteellä tai rivinvaihdolla.",
        .hiddenAppsParsedSummary:         "Tulkittu: %d sisältöhakua, %d täsmällistä",
        .fieldReducedMotion:              "Vähennä liikettä",
        .fieldPerformanceLogging:         "Suorituskykylokit",
        .fieldResetAppearance:            "Palauta ulkoasu",
        .settingsHotkey:                  "Pikanäppäin",
        .settingsBackground:              "Tausta",
        .settingsBadgeBar:                "Otsikkopalkki",
        .settingsSelection:               "Valinta",
        .settingsPreviewSize:             "Esikatselun koko",
        .settingsObjectSelector:          "Object Selector",

        .fieldLanguage:                   "Kieli",
        .launchAtLoginStatusEnabled:      "Päällä",
        .launchAtLoginStatusDisabled:     "Pois päältä",
        .launchAtLoginStatusRequiresApproval:"Odottaa hyväksyntää järjestelmäasetuksissa",
        .launchAtLoginStatusUnavailable:  "Ei saatavilla tällä macOS-versiolla",
        .launchAtLoginStatusUpdateFailed: "Muutos epäonnistui; aiempi tila palautettiin",
        .actionOpenLoginItemsSettings:    "Avaa kirjautumiskohteiden asetukset",
        .fieldModifier:                   "Muunnosnäppäin",
        .fieldTriggerKey:                 "Laukaisin",
        .fieldActiveCombo:                "Aktiivinen: %@",
        .fieldDoubleModifierSwitch:       "Pikavaihto edelliseen sovellukseen",
        .fieldDoubleModifier:             "Tuplapainalluksen näppäin",
        .shortcutConflictSpotlight:       "Komento-välilyönti on varattu Spotlightille. Valitse toinen pikanäppäin.",
        .shortcutConflictInputSource:     "Control-välilyönti on varattu syöttölähteen vaihtoon. Valitse toinen pikanäppäin.",
        .fieldColor:                      "Väri",
        .fieldOpacity:                    "Peittävyys",
        .fieldColorStrength:              "Värin voimakkuus",
        .fieldPosition:                   "Sijainti",
        .fieldAppIconColor:               "Sovelluskuvakkeen väri",
        .fieldIconSize:                   "Kuvakkeen koko",
        .fieldTextSize:                   "Tekstin koko",
        .fieldVerticalPadding:            "Pystysuora täyte",
        .fieldAnimation:                  "Animaatio",
        .fieldHighlightColor:             "Korostusväri",
        .fieldStrength:                   "Voimakkuus",
        .fieldWidth:                      "Leveys",
        .fieldMaxWidth:                   "Enimmäisleveys",
        .actionSnapWindow:                "Puolita ikkuna",
        .actionSnapLeft:                  "Vasen",
        .actionSnapRight:                 "Oikea",
        .actionSnapTop:                   "Ylös",
        .actionSnapBottom:                "Alas",
        .actionCloseWindow:               "Sulje ikkuna",
        .accessibilityWindowTileHint:     "Valitsee tämän ikkunan",
        .accessibilityApplicationTileHint:"Aktivoi tämän sovelluksen",
        .windowStateMinimized:            "Minimoitu",
        .windowStateApplication:          "Sovellus",

        .permissionMessageAccessibility:  "Salli Käyttöapu yleiseen ikkunanvaihtoon ja ikkunoiden hallintaan.",
        .permissionMessageScreenRecording:"Salli Näytön tallennus elävien ikkunaesikatselujen näyttämiseksi.",
        .permissionMessageBoth:           "Salli Käyttöapu ja Näytön tallennus kaikkien toimintojen käyttämiseksi.",
        .permissionNameAccessibility:     "Käyttöapu",
        .permissionNameScreenRecording:   "Näytön tallennus",
        .permissionActionOpenSettings:    "Avaa Järjestelmäasetukset",
        .permissionActionOpenSettingsShort:"Avaa asetukset",

        .alertPermissionTitle:            "SwitchBlade tarvitsee luvan: %@",
        .alertPermissionBody:             "SwitchBlade tarvitsee luvan toimiakseen. Puuttuvat luvat: %@. Avaa oikea Järjestelmäasetusten sivu ja salli SwitchBlade.",
        .alertOpenSettings:               "Avaa asetukset",
        .alertLater:                      "Myöhemmin",

        .modifierCommand:                 "⌘ Command",
        .modifierOption:                  "⌥ Option",
        .modifierControl:                 "⌃ Control",

        .keyTab:                          "Tab",
        .keyBacktick:                     "Aksenttipiste (`)",
        .keySpace:                        "Välilyönti",

        .windowScopeCurrentSpace:         "Nykyinen työpöytä",
        .windowScopeAllSpaces:            "Kaikki työpöydät",
        .windowScopeCurrentApp:           "Nykyinen sovellus",

        .previewModeLive:                 "Elävät esikatselut",
        .previewModeBlurred:              "Sumenna esikatselut",
        .previewModeIconsOnly:            "Vain kuvakkeet",

        .sortRecentlyUsed:                "Viimeksi käytetyt",
        .sortAppGrouped:                  "Ryhmittele sovelluksittain",
        .sortAlphabetical:                "Aakkosjärjestys",

        .loggingOff:                      "Pois",
        .loggingBasic:                    "Perus",
        .loggingDebug:                    "Vianjäljitys",

        .selectionPump:                   "Pumppu",
        .selectionBreathe:                "Hengitys",
        .selectionBounce:                 "Pomppu",
        .selectionFloat:                  "Leijunta",
        .selectionWobble:                 "Heilunta",

        .badgeBottom:                     "Alhaalla",
        .badgeTop:                        "Ylhäällä",

        .menuSecureInputOff:              "Suojattu syöttö: pois päältä",
        .menuSecureInputActive:           "Suojattu syöttö: %@ (pid %@)",
        .menuSecureInputStale:            "Suojattu syöttö jumissa pidissä %@",
        .menuSecureInputClear:            "Poista jumittunut suojattu syöttö",
        .menuSecureInputClearUnavailable: "Ei turvallista suojatun syötön siivousta",
        .menuPermissions:                 "Tarvittavat käyttöoikeudet",
        .menuOpenPermissionSettings:      "%@ – avaa Järjestelmäasetukset…",
        .menuSettings:                    "Asetukset…",
        .menuAbout:                       "Tietoja SwitchBladesta",
        .menuQuit:                        "Lopeta SwitchBlade",
        .menuSettingsWindowTitle:         "SwitchBlade-asetukset",
        .menuEdit:                        "Muokkaa",
        .menuWindow:                      "Ikkuna",
        .menuHelp:                        "Ohje",
        .menuServices:                    "Palvelut",
        .menuHide:                        "Kätke SwitchBlade",
        .menuHideOthers:                  "Kätke muut",
        .menuShowAll:                     "Näytä kaikki",
        .menuUndo:                        "Kumoa",
        .menuRedo:                        "Tee uudelleen",
        .menuCut:                         "Leikkaa",
        .menuCopy:                        "Kopioi",
        .menuPaste:                       "Sijoita",
        .menuSelectAll:                   "Valitse kaikki",
        .menuMinimize:                    "Pienennä",
        .menuZoom:                        "Zoomaa",
        .menuBringAllToFront:             "Tuo kaikki eteen",
        .tooltipSettings:                 "Asetukset",
        .tooltipSecureInputActive:        "Suojattu syöttö on käytössä sovelluksessa %@ (pid %@). Komento-sarkain voi palautua macOS:n vaihtajaan.",
        .tooltipSecureInputStale:         "Suojattu syöttö on jumissa vanhentuneessa pidissä %@. Poista se SwitchBladen valikosta.",
        .accessibilityStatusItemLabel:    "SwitchBladen tilavalikko",
        .accessibilityStatusItemHelp:     "Avaa SwitchBladen asetukset, lupatilan ja sovelluksen hallintatoiminnot.",
        .accessibilitySwitcherPanelLabel: "SwitchBladen ikkunanvaihtaja",
        .aboutBuiltAt:                    "Koottu"
    ]
}
