#!/bin/zsh

export SWITCHBLADE_CODESIGN_SUPPORT_DIR="${SWITCHBLADE_CODESIGN_SUPPORT_DIR:-$HOME/Library/Application Support/SwitchBlade/codesign}"
export SWITCHBLADE_CODESIGN_PASSWORD_FILE="${SWITCHBLADE_CODESIGN_PASSWORD_FILE:-$SWITCHBLADE_CODESIGN_SUPPORT_DIR/keychain-password.txt}"
export SWITCHBLADE_CODESIGN_CERTIFICATE="${SWITCHBLADE_CODESIGN_CERTIFICATE:-$SWITCHBLADE_CODESIGN_SUPPORT_DIR/certificate.pem}"
export SWITCHBLADE_CODESIGN_PRIVATE_KEY="${SWITCHBLADE_CODESIGN_PRIVATE_KEY:-$SWITCHBLADE_CODESIGN_SUPPORT_DIR/private-key.pem}"
export SWITCHBLADE_CODESIGN_ARCHIVE="${SWITCHBLADE_CODESIGN_ARCHIVE:-$SWITCHBLADE_CODESIGN_SUPPORT_DIR/identity.p12}"
export SWITCHBLADE_CODESIGN_FINGERPRINT_FILE="${SWITCHBLADE_CODESIGN_FINGERPRINT_FILE:-$SWITCHBLADE_CODESIGN_SUPPORT_DIR/certificate-sha1.txt}"
export SWITCHBLADE_CODESIGN_IDENTITY_NAME="${CODESIGN_IDENTITY_NAME:-SwitchBlade Local Codesign}"
export SWITCHBLADE_SIGNING_LOCK_FILE="${SWITCHBLADE_SIGNING_LOCK_FILE:-$SWITCHBLADE_CODESIGN_SUPPORT_DIR/signing.lock}"
